task_name: secknowledge2_vanilla
created_by: IBM Research
data_builder: secknowledge2
task_description: Reformats the responses of a general instruction dataset (the one used in the original paper of [ReAlign](https://arxiv.org/abs/2402.12219)) into a format that better aligns with pre-established criteria and collected evidence.
retriever:
  type: core/web/duckduckgo
  limit: 2
  process_webpages: True
  deduplicate_sources: True
  reorder_organic: True
  webpage_processor: docling
max_queries_per_instruction: 2
summarize_web_results: False
templates_dir: data/public/secknowledge2/templates/vanilla
seed_datastore:
  type: default
  data_path: ${DGT_DATA_DIR}/public/secknowledge2/example_data_vanilla.json
