repos:
  # isort: sorts imports
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # Black: formats Python code consistently
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  # Ruff: lints and fixes minor issues
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --fix, --config=pyproject.toml]

  # Prettier: formats non-Python files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
