databuilders:
  simple: # <-- your databuilder name should go here
    blocks:
      - name: generator # <-- the name of the llm generator in your databuilder should go here
        type: watsonx
        model_id_or_path: mistralai/mistral-medium-2505
